ALTER TABLE places ADD COLUMN IF NOT EXISTS osm_surface VARCHAR(50);
ALTER TABLE places ADD COLUMN IF NOT EXISTS osm_incline VARCHAR(20);
ALTER TABLE places ADD COLUMN IF NOT EXISTS osm_entrance_wheelchair VARCHAR(20);
ALTER TABLE places ADD COLUMN IF NOT EXISTS osm_kerb_tactile BOOLEAN;
